# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 14 Jan 2025 07:15:27 +0000
*               @ALL          1
*               @user         8
