<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Thu, 16 Jan 2025 14:08:57 +0100
 */

$conf['title'] = 'Projekt ISZ - CRM';
$conf['template'] = 'bootstrap3';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['plugin']['clock']['helpbar'] = 0;
$conf['plugin']['translation']['translations'] = 'pl en';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'cosmo';
$conf['tpl']['bootstrap3']['sidebarPosition'] = 'right';
$conf['tpl']['bootstrap3']['sidebarOnNavbar'] = 1;
$conf['tpl']['bootstrap3']['showTranslation'] = 1;
$conf['tpl']['bootstrap3']['showHomePageLink'] = 1;
$conf['tpl']['bootstrap3']['fluidContainer'] = 0;
$conf['tpl']['bootstrap3']['tocCollapsed'] = 1;
$conf['tpl']['bootstrap3']['showPageInfo'] = 0;
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,microsoft-teams,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
$conf['tpl']['bootstrap3']['collapsibleSections'] = 1;
