# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 14 Jan 2025 07:15:27 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$Af3tAiDkO0lqTQFg4Pgvve7JhdBJpD0VUh1p0pD/WPFxeH3nGjM0W:Mateusz Mróz:matik.mroz@gmail.com:admin,user
